//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTrackingWebAPI.Repository.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TT=TaskTrackingWebAPI.Core.Model;
    
    public partial class TaskDBEntities : DbContext
    {
        public TaskDBEntities()
            : base("name=TaskDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TT.Task> Tasks { get; set; }
        public virtual DbSet<TT.User> Users { get; set; }
    }
}
